server:
  port: 8089
    #配置证书
  #这里是配置你刚才部署在resources下的".jks"文件
  ssl:
    key-store: classpath:6191236_www.wuxianliuliang.cn.jks
    key-store-password: 2wgs0cOy
    key-store-type: JKS


spring:
  application:
    name: collection-server
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: system
  key:
    admin: 'ums:admin'
    app: 'app:admin'
    resourceList: 'ums:resourceList'
    authCode: "app:authCode:"
  expire:
    common: 86400 # 24小时
    authCode: 60 # 验证码超期时间

logging:
  file:
    name: D:/evn/exe
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /app/member/getAuthCode
      - /app/member/verifyAuthCode
      - /app/member/serialNumberGeneration
      - /app/member/appRegister
      - /app/member/appLogin
      - /app/member/updatePassword
      - /app/umsUniAddress/list
      - /app/umsUniAddress/create
      - /app/umsUniAddress/{id}
      - /app/umsUniAddress/update
      - /app/umsUniAddress/update/{id}
      - /app/umsUniAddress/delete/{id}
      - /app/umsUniAddress/updateStatus/{id}
      - /dictionary/getDictionaryByType
      - /area/listAll
      - /weChat/auth
      - /weChat/getOpenId


