spring:
  datasource:
    url: jdbc:mysql://localhost:3306/information_collect?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123
  redis:
    host: localhost # Redis服务器地址
    database: 7 # Redis数据库索引（默认为0）
    port: 16379 # Redis服务器连接端口
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）


logging:
  file:
    path: /var/logs
  level:
    root: info
    com.hst.johns.collection : debug


wx:
  mp:
    configs:
      - appId: wx6a5b4901ea3f40d7
        secret: 40e61b910b431841e15b4aa3d1ccfcc2
        token: Authorization
        aesKey: ObpYGWaXjfs6eoht5cUXNFjd5C5Y2tOq2K5tO9ZwEtg
