spring:
  datasource:
    url: jdbc:mysql://localhost:3306/information_collect?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost # Redis服务器地址
    database: 7 # Redis数据库索引（默认为0）
    port: 16379 # Redis服务器连接端口
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.hst.johns.collection : debug
