spring:
  datasource:
    url: jdbc:mysql://rm-m5e1371agd3588sgm8o.mysql.rds.aliyuncs.com:3306/information_collect_pro?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: r-bp1qmog73tcsp7ifrfpd.redis.rds.aliyuncs.com # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 16379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.hst.johns.collection : debug
